### ISSUE TITLE
LaunchXFCE_proot error

### ISSUE THREAD

**Issue by maskelog** [cheadrian/termux-chroot-proot-wine-box86_64#1]
termux-x11: no process found
Xwayland: no process found
virgl_test_server: no process found
/data/data/com.termux/files/home/.shortcuts/LaunchXFCE_proot: 3: termux-toast: not found
how do I fix it?

**Comment by cheadrian** [comment]
`no process found` is normal if the process is not running. The LaunchXFCE_proot script try to kill everything that can interfere with the launch.
As for termux-toast: not found, you can install [Termux:API](https://wiki.termux.com/wiki/Termux:API) and the [termux-toast](https://wiki.termux.com/wiki/Termux-toast) package. Check [Termux:Widget shortcut](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/blob/425a8a64d12cbfb006667e3a5882e1ebe8c378bb/Setup_Proot.md#termuxwidget-shortcut).

These aren't mandatory, and you can ignore both the `no process found` and `not found` in these cases.

If you have problem with launching the XFCE proot, then maybe your installation was interrupted at some point. You should try a clean install by deleting Termux data, or, at last, the proot and re-run installation script.
