### ISSUE TITLE
Chroot Launch and Kill Shortcut

### ISSUE THREAD

**Issue by Styx3** [cheadrian/termux-chroot-proot-wine-box86_64#10]
for chroot setup, tried to update shortcut files multiple times but it doesn't seems to work. every time I'm getting same result.
```
termux-x11: no process found
Xwayland: no process found
pulseaudio: no process found
virgl_test_server_android: no process found
```
I know this log doesn't means anything as before launching it tries to kill existing ones but this is only message I get and terminal freezes. on the  other hand I'm able to run commands manually and start desktop environment. shortcuts would be nice to have :')

**Comment by cheadrian** [comment]
The log is normal, as the script tries to kill everything that is related to it.
I can't help you with the chroot, as there can be a setup difference between devices.
I suggest you to use proot variant, as chroot isn't necessary much faster, depends on the access to the GPU driver of your device has on chroot vs. proot.
You can read the insigns from my venture in the markdown files on this repo, for both [chroot](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/blob/main/Setup_Chroot_Magisk.md) and [proot](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/blob/main/Setup_Proot.md).
