### ISSUE TITLE
Black screen with termux x11 on chroot

### ISSUE THREAD

**Issue by zhinu** [cheadrian/termux-chroot-proot-wine-box86_64#12]
Hi After following the tutorial, I have the following error and a black screen with the mouse as a cross:

![image](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/assets/75084558/36911cd5-4347-4051-ba5b-affb3314a930)

```
dbus-launch --exit-with-session startxfce4 &
[1] 5179
root@linux:~# /usr/bin/startxfce4: X server already running on display :0
xrdb: Connection refused
xrdb: Can't open display ':0'
Unable to init server: Could not connect: Connection refused
xfce4-session: Cannot open display: .
Type 'xfce4-session --help' for usage.
```

 ```
neofetch
         -o          o-            u0_a173@linux
          +hydNNNNdyh+             -------------
        +mMMMMMMMMMMMMm+           OS: Android 10 aarch64
      `dMMm:NMMMMMMN:mMMd`         Host: Hisense HITV105C
      hMMMMMMMMMMMMMMMMMMh         Kernel: 4.14.133
  ..  yyyyyyyyyyyyyyyyyyyy  ..     Uptime: 6 hours, 5 mins
.mMMm`MMMMMMMMMMMMMMMMMMMM`mMMm.   Packages: 138 (dpkg), 1 (pkg)
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Shell: bash 5.2.15
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   CPU: Unisoc ums512 (8) @ 1.820GHz
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:   Memory: 2030MiB / 4096MiB
:MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM:
-MMMM-MMMMMMMMMMMMMMMMMMMM-MMMM-
 +yy+ MMMMMMMMMMMMMMMMMMMM +yy+
      mMMMMMMMMMMMMMMMMMMm
      `/++MMMMh++hMMMM++/`
          MMMMo  oMMMM
          MMMMo  oMMMM
          oNMm-  -mMNs
```

Amyone has any idea how to troubleshoot?

**Comment by cheadrian** [comment]
You didn't get any error while installing, correct?

How you start the session? Using built in alias `start_box_proot`?

First, close everything.
`pkg install -y termux-x11-nightly mesa-demos` then open the Termux x11 Android app, go back to Termux, `XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :0 -ac &` and try to `DISPLAY=:0 glxgears`

**Comment by zhinu** [comment]
> First, close everything.
> pkg install -y termux-x11-nightly mesa-demos then open the Termux x11 Android app, go back to Termux, XDG_RUNTIME_DIR=${TMPDIR} termux-x11 :0 -ac & and try to DISPLAY=:0 glxgears
This works for me,

> How you start the session? Using built in alias start_box_proot?
I start the session with `sudo bootlinux`

**Comment by cheadrian** [comment]
Ok, so you use the chroot variant, then I can't assist you with more than it's already written on markdown files.

You can try the [proot variant first](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/tree/main#getting-started), as it will automatically set up everything.
