### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by shubham1244** [cheadrian/termux-chroot-proot-wine-box86_64#18]
Running step: install_termux_x11_pkg_app.
Install Termux:X11 companion and apk.
Note: you can get the latest version from termux/termux-x11 Github.
--2023-10-29 16:14:57--  https://github.com/termux/termux-x11/releases/download/1.03.00/app-universal-debug.apk
Resolving github.com (github.com)... 20.207.73.82
Connecting to github.com (github.com)|20.207.73.82|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-10-29 16:14:57 ERROR 404: Not Found.

install_termux_x11_pkg_app encountered an error.
Please use the 'cd termux-chroot-proot-wine-box86_64', './Scripts/Addons_Menu.sh' and select remove script or delete Termux App data and try again.
Error can be from network, incompatibility, outdated 'X11_APK_LINK', 'X11_COMPANION_LINK' or script problem due Termux / Android updates.
~ $

**Comment by cheadrian** [comment]
Fixed in https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/commit/6007e5e1387d5b7f8bb97c7c93e0792e8dd8b25e.
