### ISSUE TITLE
Cannot install the script

### ISSUE THREAD

**Issue by DieLokki** [cheadrian/termux-chroot-proot-wine-box86_64#2]
--2023-07-13 18:06:58--  https://nightly.link/termux/termux-x11/actions/artifacts/616957082.zip
Resolving nightly.link (nightly.link)... 45.32.185.199, 2001:19f0:5001:3a1:5400:ff:fe59:31d1
Connecting to nightly.link (nightly.link)|45.32.185.199|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-07-13 18:06:59 ERROR 404: Not Found.

It gives me an error on this phase

**Comment by cheadrian** [comment]
Looks like the nightly.link artifact download link is not valid anymore. I'll update it shortly.

**Comment by DieLokki** [comment]
@cheadrian The installation process was a success. Have you considered an offline installation solution to avoid this issue in the future?
I also had another installation failure which I specify in another ticket
