### ISSUE TITLE
Cannot execute ./Scripts/Addons_Menu.sh

### ISSUE THREAD

**Issue by DieLokki** [cheadrian/termux-chroot-proot-wine-box86_64#4]
It says that there is no such file or directory

**Comment by cheadrian** [comment]
You run this from inside the `termux-chroot-proot-wine-box86_64` directory? 
`cd termux-chroot-proot-wine-box86_64` first.

**Comment by DieLokki** [comment]
No, the instruction were unclear of needing to cd there first

**Comment by cheadrian** [comment]
2766b70
