### ISSUE TITLE
Why decrypted `/data` is required?

### ISSUE THREAD

**Issue by Young-Lord** [cheadrian/termux-chroot-proot-wine-box86_64#6]
In `Setup_Chroot_Magisk.md`, `Device /data - /userdata - is not encrypted;` is required. However, it's hard to do this on some special devices. So, could you please tell me which step requires it? Thanks!

**Comment by cheadrian** [comment]
You can use the proot method.
_"Magisk does not support user context changes on encrypted data partitions, which leads to errors when connecting to the Kali rootfs via ssh (i.e. “Required key not available”) if the data partition is encrypted."_

**Comment by Young-Lord** [comment]
thanks!
