### ISSUE TITLE
how to install zink+turnip from proot-distro

### ISSUE THREAD

**Issue by hansm629** [cheadrian/termux-chroot-proot-wine-box86_64#8]
![스크린샷_2023-07-24_11-35-28](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/assets/101167173/8707e466-d072-42fb-873a-2efb2000a618)

Galaxy S23 Ultra, Galaxy Tab S8+ 5G
After installing Ubuntu 22.04 LTS through termux proot-distro

XFCE4 SESSION is in use via termux-x11 xwayland.

virglrenderer-android performance is too low and OpenGL2.1 limited, so I'm trying to accelerate GPU through zink+turnip.
I have two questions.

**Q1. I'm curious about the 'meson build' options for A7xx zink+turnip support.**
I'd like to know what the 'meson build' option is for A7xx zink+turnip support.

**Q2. I'm curious about the command to run zink+turnip after build.**
I want to know the command to execute zink+turnip after going through the Q1 process.
```c
DISPLAY=:0 MESA_LOADER_DRIVER_OVERRIDE=zink TU_DEBUG=noconform MESA_VK_WSI_DEBUG=sw
``` 
Should I execute it as a command?

**Comment by cheadrian** [comment]
You can find information here: [Hardware Acceleration Resources](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/blob/main/Hardware_Acceleration_Resources.md#hardware-acceleration-resources).

You don't need to compile the _mesa_ by yourself, because there's a Zink compatible mesa package inside [tur-repo](https://github.com/termux-user-repository/tur). If you want to, you can check build instructions from the [mesa-zink package](https://github.com/termux-user-repository/tur/tree/master/tur/mesa-zink).

Or you can run the [Addons_Menu.sh](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/blob/main/Scripts/Addons_Menu.sh) and select option _4. Termux: Set-up mesa-zink and compatible virgl server._.

**Comment by hansm629** [comment]
> 



> You can find information here: [Hardware Acceleration Resources](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/blob/main/Hardware_Acceleration_Resources.md#hardware-acceleration-resources).
> 
> You don't need to compile the _mesa_ by yourself, because there's a Zink compatible mesa package inside [tur-repo](https://github.com/termux-user-repository/tur). If you want to, you can check build instructions from the [mesa-zink package](https://github.com/termux-user-repository/tur/tree/master/tur/mesa-zink).
> 
> Or you can run the [Addons_Menu.sh](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/blob/main/Scripts/Addons_Menu.sh) and select option _4. Termux: Set-up mesa-zink and compatible virgl server._.


meesa-zink and mesa-zink-vulkan-icd-freedreno in tur-repo do not work on the A7xx series. T_T

And if what I know is right
I understand that mesa-zink and mesa-zink-vulkan-icd-freedreno are not packages for proot-distro, but packages for termux, termux-x11.

In addition to virgl, you want to implement GPU acceleration in a proot-distro environment.


From proot-distro Ubuntu, use the meson build option below
I wonder if zink and turnip can be activated.

```c
meson build -D platforms=x11,wayland -D gallium-drivers=swrast,virgl,zink -D vulkan-drivers=freedreno -D dri3=enabled -D egl=enabled -D gles2=enabled -D glvnd=true -D glx=dri -D libunwind=disabled -D osmesa=true -D shared-glapi=enabled -D microsoft-clc=disabled -D valgrind=disabled --prefix /usr -D gles1=disabled -D freedreno-kmds=kgsl -Dbuildtype=release
``` 
```c
ninja -C build install
``` 

"-D gallium-drivers=swrast,virgl,zink" 
"-D vulkan-drivers=freedreno"
"-D freedreno-kmds=kgsl"

Should I add an option?

**Comment by cheadrian** [comment]
I can't provide more assistance for this subject, as that isn't the purpose of this repo.

You can ask for help on the [Termux subreddit](https://www.reddit.com/r/termux). A search for Zink or Turnip on that sub should give you insights that you need. Also, check the links at the bottom of the [mentioned file](https://github.com/cheadrian/termux-chroot-proot-wine-box86_64/blob/main/Hardware_Acceleration_Resources.md#relevant-links).

> I understand that mesa-zink and mesa-zink-vulkan-icd-freedreno are not packages for proot-distro, but packages for termux, termux-x11.
This is how it should be, as you can't access the GPU directly from proot. To have GPU support inside proot, you should use a proxy like [VirGL](https://docs.mesa3d.org/drivers/virgl.html) or the [Virtio-GPU Venus](https://docs.mesa3d.org/drivers/venus.html).
