### ISSUE TITLE
LaunchXFCE_proot issue

### ISSUE THREAD

**Issue by Abidzar16** [cheadrian/termux-chroot-proot-wine-box86_64#9]
This is related to Setup_Proot.md. Apparently, I am unable to open an internet browser inside Linux, is there any way to fix this?

**Comment by cheadrian** [comment]
Did you install any internet browser inside the proot?
`apt install firefox`

**Comment by Abidzar16** [comment]
Done, but then it asks me to install Firefox via Snap

**Comment by cheadrian** [comment]
`apt install firefox-esr` [(1)](https://www.reddit.com/r/termux/comments/xc8w3k/cant_run_firefox_on_prootdistro/)
This is not related to the script purpose.
